### ISSUE TITLE
x86 support

### ISSUE THREAD

**Issue by soredake** [mpv-android/buildscripts#10]
@sfan5

**Comment by sfan5** [comment]
it *can* be supported, but it's probably no good in practice
```
<JEEB> IA32 is a bitch
<JEEB> because Google from I think android 6 started requiring PIC
<JEEB> which is incompatible with how FFmpeg writes hand-written assembly (with 32bit)
<JEEB> https://trac.ffmpeg.org/ticket/4928
<JEEB> you can --disable-asm for it, but at that point if you're dealing with x86 devices I'm not really sure how worth that is
<JEEB> but yea, support can be added as far as "it's going to be slow as molasses with anything that has to do with CPU work for decoding/filtering"
<JEEB> the cross-prefix should be i686-xxx-* instead of x86_64-xxx-* and FFmpeg would require disable-asm
```

**Comment by sfan5** [comment]
Here's an ia32-only build, don't expect it to work well without hwdec
[mpv-android_i686.apk.zip](https://github.com/mpv-android/buildscripts/files/1545699/mpv-android_i686.apk.zip)

**Comment by soredake** [comment]
@sfan5 working fine with 30fps local and youtube videos.

**Comment by hatharry** [comment]
android n still has text relocation errors

**Comment by sfan5** [comment]
This was built with `--disable-asm` as suggested by @jeeb, maybe `--disable-pic` is needed too?

**Comment by hatharry** [comment]
no need for --disable-asm. The apk needs to set to release (not debug) and signed. Tested with android-x86
