### ISSUE TITLE
Android SDK installed with these scripts lacks licenses

### ISSUE THREAD

**Issue by xyzz** [mpv-android/buildscripts#4]
As a result the build command complains about it and does not build:

```
Checking the license for package Android SDK Build-Tools 25.0.2 in /home/xyz/mpv-android/sdk/android-sdk-linux/licenses
Warning: License for package Android SDK Build-Tools 25.0.2 not accepted.
Checking the license for package Android SDK Platform 25 in /home/xyz/mpv-android/sdk/android-sdk-linux/licenses
Warning: License for package Android SDK Platform 25 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Build-Tools 25.0.2, Android SDK Platform 25].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
```

Apparently the root cause is this:

> Note: Accepting the license agreements using the android command line tool does not create this licenses directory. You must first accept the agreements using the SDK Manager to be able to use this feature.

https://developer.android.com/studio/intro/update.html#download-with-gradle

There's also the following answer: https://stackoverflow.com/a/43039679. However, our android sdk is too old, it might be a good time to update it.

**Comment by Transfusion** [comment]
The SDK downloaded using ```download.sh``` didn't contain any build-tools or target platforms (in particular API 25). ```echo 'y' | ./tools/android update sdk --no-ui --all --filter build-tools-25.0.2, android-25``` accepted the license on the CLI for me; ```./buildall.sh --no-deps  mpv-android``` subsequently worked even though no licenses folder was created in the ```sdk``` directory.

**Comment by xyzz** [comment]
I had to do `echo 'y' | ./tools/android update sdk --no-ui --all --filter build-tools-25.0.2,android-25,platform-tools` with the latest installation to make it work.
