### ISSUE TITLE
more complete dependency list

### ISSUE THREAD

**Issue by Cauterite** [mpv-android/buildscripts#5]
from a fresh installation of **Debian 8.8** i was able to build a working APK, so the download and build scripts seem to be working pretty nicely. however, it took a lot of trial and error to work out exactly what other tools were required.

maybe this seems like standard stuff, but a linux novice like me isn't going to be able to anticipate all of these items, and will instead find out the hard way. having them listed in the readme would be much more convenient.

packages that i had to install:

	apt-get install sudo
	apt-get install unzip
	apt-get install git
	apt-get install pkgconf
	apt-get install automake
	apt-get install libtool

	openjdk-8-jdk ?
	( https://xmoexdev.com/wordpress/installing-openjdk-8-debian-jessie/ )

the process also consumed something like 10 or 20 GB of disk space (which i didn't anticipate; i had to extend my disk partition)

and there was the matter of issue #4 

---

so overall i'm very happy that i was able to get this built having never compiled an android app before (and quite limited linux experience), but i think putting this extra information in the readme would be helpful for others attempting to do the same.

**Comment by sfan5** [comment]
pretty much solved by 5abca7c576b72dc28a07f138f789c21174fd103d
